// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twgyugnrzpslgjkopfxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3Z3l1Z25yenBzbGdqa29wZnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODY0MTksImV4cCI6MjA2NTM2MjQxOX0.ZjGPoD861mu9rw_2ikucFP-CMrlhI6IJzy5-oxcC-Dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);